//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OasisInstagram.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OasisInstagram.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   var scrollHeightEnd = 0;
        ///var isFinish = false;
        ///var myInterval = setInterval(function(){
        ///    loadingSvg = document.querySelector(&quot;div[data-visualcompletion=loading-state]&quot;)
        ///    scrollDiv = document.querySelector(&quot;div &gt; div &gt; div &gt; div &gt; div &gt; div &gt; div &gt; div._aano&quot;)
        ///    scrollHeight = scrollDiv.scrollHeight
        ///    scrollDiv.scrollTo(0,scrollHeight)    
        ///    console.log(&quot;scrolling&quot;)
        ///    if(scrollHeightEnd == scrollHeight &amp;&amp; loadingSvg == null)
        ///    {
        ///        clearInterval(myInterval);
        ///        console.lo [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GetUsersFromUser {
            get {
                return ResourceManager.GetString("GetUsersFromUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   var scrollHeightEnd = 0;
        ///var isFinish = false;
        ///var myInterval = setInterval(function(){
        ///    loadingSvg = document.querySelector(&quot;div[data-visualcompletion=loading-state]&quot;)
        ///    scrollDiv = document.querySelector(&quot;div &gt; div &gt; div &gt; div &gt; div &gt; div &gt; div &gt; div._aano&quot;)
        ///    scrollHeight = scrollDiv.scrollHeight
        ///    scrollDiv.scrollTo(0,scrollHeight)    
        ///    console.log(&quot;scrolling&quot;)
        ///    if(scrollHeightEnd == scrollHeight &amp;&amp; loadingSvg == null)
        ///    {
        ///        clearInterval(myInterval);
        ///        console.lo [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MyFollowers {
            get {
                return ResourceManager.GetString("MyFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   var scrollHeightEnd = 0;
        ///var isFinish = false;
        ///var myInterval = setInterval(function(){
        ///    loadingSvg = document.querySelector(&quot;div[data-visualcompletion=loading-state]&quot;)
        ///    scrollDiv = document.querySelector(&quot;div &gt; div &gt; div &gt; div &gt; div &gt; div &gt; div &gt; div._aano&quot;)
        ///    scrollHeight = scrollDiv.scrollHeight
        ///    scrollDiv.scrollTo(0,scrollHeight)    
        ///    console.log(&quot;scrolling&quot;)
        ///    if(scrollHeightEnd == scrollHeight &amp;&amp; loadingSvg == null)
        ///    {
        ///        clearInterval(myInterval);
        ///        console.lo [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MyFollows {
            get {
                return ResourceManager.GetString("MyFollows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   const interval = 5000;
        ///    cur_tick = 0;
        ///    butonClicked = false;
        ///
        ///	   var readyStateCheckInterval = setInterval(function() {
        ///	   if (document.readyState === &quot;complete&quot;) {
        ///	    cur_tick += interval/1000;	
        ///
        ///		unfollow();
        ///
        ///	   }
        ///
        ///	}, interval);
        ///
        ///	
        ///
        ///
        ///    function unfollow()
        ///    {
        ///        isDialogOpen = document.querySelector(&quot;div[role = dialog]&quot;)
        ///        isUnfollowButton = document.querySelector(&quot;div &gt; span &gt; span._abgm._abn8 &gt; button&quot;).innerText == &apos;&apos;
        ///        if(!butonClicked &amp;&amp; isUnfollowButton) 
        ///        {
        /// [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Unfollow {
            get {
                return ResourceManager.GetString("Unfollow", resourceCulture);
            }
        }
    }
}
